define: 
  - &model_file 'unet.model'
  - &structure 'annular'

workdir: './wd/'
variables_annular: &variables
  - name: r
    type : vreal
    lower: -0.5
    upper: 0.5
    size: 4
  - name: w
    type : vreal
    lower: 0.0
    upper: 1.2
    size: 4
  - name: dpillar
    type : real
    lower: 0.0
    upper: 1.2

datasets:
  - &template-pop
    name: doe 
    storages:
      - metric
      - epsilon_map
      - leakage_map
    variables: *variables
    exporters:
      npz.maps: ["epsilon_map", "leakage_map"]
    populate-on-creation:
      algo: LHS
      count: 50
  - <<: *template-pop
    populate-on-creation: false
    name: main
  - <<: *template-pop
    name: selected
    populate-on-creation: false
      
algorithms:
  - name: unet
    actions:
      - name: train
        type: script_runner
        shell: sbatch
        parallel: false
        path: user/templates/submit_unet.proto.sh
        workdir: "./wd/"
    config:
      model_file: *model_file
      epochs: 200
      hours: 1
      complexity: 3
      angle: 90
      decay: 1e-5
      batch_size: 64
      lr: 5e-4
      validratio: 0.05
  - name: fom
    actions:
      - type: module_runner
        name: evaluate-unet
        shell: false
        path: user.unet_inference
        workdir: "./wd/"
      - type: sequence_runner
        name: evaluate-fdtd
        actions:
          - type: module_runner 
            name: input
            shell: false
            path: user.process_input
            workdir: "./wd/"
          - type: script_runner
            name: fdtd-job
            shell: sbatch
            parallel: false
            path: user/templates/submit_simulation.proto.sh
            workdir: ./wd/
          - type: module_runner
            name: output
            shell: false
            path: user.process_output
            workdir: "./wd/"


    config:
      type: *structure
      workdir: "./wd/"
      resolution: 10
      variables: *variables
  - name: pso
    actions:
      - name: run
        type: script_runner
        shell: sbatch
        parallel: false
        path: user/templates/submit_optimize.proto.sh
        workdir: "./wd/"

    config:
      fevals: 40000
      model: *model_file
      nagents: 40
  - name: sel
    actions:
      - type: script_runner
        name: run
        shell: sbatch
        parallel: false
        path: user/templates/submit_selection.proto.sh
        workdir: "./wd/"
    config:
      num_clusters: 4
      selection_size: 5
      model: *model_file



